// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Animal struct {
	ID    string `json:"id"`
	Hello string `json:"hello"`
}

func (Animal) IsEntity() {}

type Query struct {
}
