package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"main/graph/model"
)

// Animals is the resolver for the animals field.
func (r *queryResolver) Animals(ctx context.Context) ([]*model.Animal, error) {
	return []*model.Animal{
		{
			ID:   "1",
			Name: "Dog",
		},
		{
			ID:   "2",
			Name: "Cat",
		},
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
